services:
  db:
    image: mysql:latest
    container_name: db_c
    environment:
      MYSQL_HOST: ${DATABASE_HOST}
      MYSQL_ROOT_PASSWORD: ${USER}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin
    container_name: pma_c
    links:
      - db
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - ${REDIS_SERVER_PORT}:${REDIS_SERVER_PORT}
      - 8001:8001

  gateway:
    build: .
    environment:
      DATABASE_URL: mysql://root:root@db:${MYSQL_PORT}/food?schema=public
    container_name: gateway_c
    ports:
     - ${GATEWAY_PORT}:${GATEWAY_PORT}
    healthcheck:
      test: "wget --spider http://localhost:3000/health || exit 1"
    depends_on:
      db:
        condition: service_healthy

  category-microservice:
    build:
      context: .
      args:
        NAME: start category-microservice
        TSCONFIG: --path apps/microservice/apps/category/tsconfig.app.json
        CLI: --config apps/microservice/nest-cli.json
    environment:
      REDIS_HOST: redis-stack
      GRAPHQL_GATEWAY_HOST: 'gateway-graphql'
    container_name: category_microservice_c
    ports:
     - ${CATEGORY_MICROSERVICE_PORT}:${CATEGORY_MICROSERVICE_PORT}
    depends_on:
      gateway:
        condition: service_healthy

  category-graphql:
    build:
      context: .
      args:
        NAME: start category-graphql
        TSCONFIG: --path apps/graphql/apps/share/apps/category/tsconfig.app.json
        CLI: --config apps/graphql/apps/share/nest-cli.json
    container_name: category_graphql_c
    environment:
      CATEGORY_GRAPHQL_PORT: ${CATEGORY_GRAPHQL_PORT}
      DATABASE_URL: mysql://root:root@db:${MYSQL_PORT}/food?schema=public
    ports:
      - ${CATEGORY_GRAPHQL_PORT}:${CATEGORY_GRAPHQL_PORT}
    healthcheck:
      test: "wget --spider http://localhost:3003/health || exit 1"
    depends_on:
      - db

  gateway-graphql:
    build:
      context: .
      args:
        NAME: start gateway-graphql
        TSCONFIG: --path apps/graphql/apps/gateway/tsconfig.app.json
        CLI: --config apps/graphql/nest-cli.json
    container_name: gateway_graphql_c
    environment:
      CATEGORY_GRAPHQL_URL: 'http://category-graphql:${CATEGORY_GRAPHQL_PORT}/graphql'
      GRAPHQL_GATEWAY_HOST: 'gateway-graphql'
    ports:
      - ${GRAPHQL_GATEWAY}:${GRAPHQL_GATEWAY}
    depends_on:
      category-graphql:
        condition: service_healthy
